package com.example.backend.Exception;

public enum ErrorCodes {
	//Administrateur
	ADMININSTRATEUR_NOT_FOUND(1000),
	ADMINISTRATEUR_INVALID(1001),
	ADMINISTRATEUR_ALREADY_EXISTE(1002),

	//Role
	ROLE_NOT_FOUND(2000),
	ROLE_INVALID(2001),
	ROLE_ALREADY_EXISTE(2002),

	//Activite
	ACTIVITE_NOT_FOUND(3000),
	ACTIVITE_ALREADY_EXISTE(3001),
	ACTIVITE_INVALID(30002),

	//Exercice
	EXERCICE_NOT_FOUND(4000),
	EXERCICE_INVALID(4001),
	EXERCICE_ALREADY_EXISTE(4002),

	//Participant
	PARTICIPANT_NOT_FOUND(5000),
	PARTICIPANT_INVALID(5001),
	PARTICIPANT_ALREADY_EXISTE(5002),

	//Participation
	PARTICIPATION_NOT_FOUND(6000),
	PARTICIPATION_INVALID(6001),
	PARTICIPATION_ALREADY_EXISTE(6002),

	//Responsable
	RESPONSABLE_NOT_FROUND(7000),
	RESPONSABLE_INVALID(7001),
	RESPONSABLE_ALREADY_EXISTE(7002);
	private int code;
	ErrorCodes(int code) {
		this.code = code;
	}
	public int getCode() {
		return code;
	}
}
